// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitializeBusiness() (*Business, error) {
	db := NewDB()
	dao := NewDao(db)
	business, err := NewBusiness(dao)
	if err != nil {
		return nil, err
	}
	return business, nil
}
